### ISSUE TITLE
Question about real time events

### ISSUE THREAD

**Issue by victorm95** [feathersjs/feathers-chat-vuex#1]
How configure realtime events?
The examples is not using real time events (using rest provider), and [feathers-chat-vuex](https://github.com/feathersjs/feathers-chat-vuex) neither.

I try to configure the real time events in a simple test app, but I have a strange behavior.
I can listen for socket events and refresh de data with the actions, but that returns duplicated data.

For example:

Send `{ message: 'Hi!' }`
Send `{ message: 'Hello!' }`
Receive
```
[
  { message: 'Hi!' },
  { message: 'Hello!' },
  [ { message: 'Hi!' }, { message: 'Hello!' } ]
]
```
The basic test app [feathers-vuex-test](https://github.com/victorm95/feathers-vuex-test)

**Comment by marshallswain** [comment]
Hi @victorm95.  Realtime events are actually handled by the [`feathers-reactive`](https://github.com/feathersjs/feathers-reactive) plugin.  `feathers-chat-vuex` is using it, here: https://github.com/feathersjs/feathers-chat-vuex/blob/master/src/api/feathers-client.js#L17

**Comment by marshallswain** [comment]
By the way, thanks for pointing this out.  I added a note to the `feathers-vuex` readme: https://github.com/feathersjs/feathers-vuex#handling-realtime-events

**Comment by victorm95** [comment]
Thanks for reply.

I clone this repo and the real time events doesn't work.
I send messages from jQuery client and another vuex client but the message list still in 0, I have to refresh the page to get the messages.

Another thing, the package.json doesn't have the feathers-vuex dependency.

**Comment by marshallswain** [comment]
Oh thanks for catching that the `feathers-vuex` dependency was missing.  I was using an npm linked version when I published.  ;)

I'll check the realtime stuff.  It was working last I tried.

**Comment by marshallswain** [comment]
Hey, @victorm95.  Thanks for reporting on this.  I made a new release of `feathers-vuex` with some changes to how RxJS Observables are handled and updated `feathers-chat-vuex`.  Can you pull the latest changes and try again?

**Comment by victorm95** [comment]
Great. Now is working.

Thank you very much.

**Comment by marshallswain** [comment]
Awesome.  I'm so glad you reported.  Thank you!
