### ISSUE TITLE
Socket IO failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by valentinbica** [feathersjs/feathers-chat-vuex#3]
I've just used boilerplate code for here. 

```
npm install
npm run dev
```

I receive Error in connection establishment: net::ERR_CONNECTION_REFUSED for websocket connection

Any ideas ?

**Comment by marshallswain** [comment]
@valentinbica the WebSocket error is most likely from not having a Feathers server running.  This project is designed to work alongside the [`feathers-chat` repo](https://github.com/feathersjs/feathers-chat).  You'll just need to clone that repo, `npm install`, and `npm start`, I think.  Please reopen this issue if that doesn't fix the problem.  I'll make a note in the readme.
