### ISSUE TITLE
Router mode history

### ISSUE THREAD

**Issue by lobosan** [feathersjs/feathers-chat-vuex#4]
Hi, I'm playing around with this example and updated the router (/src/router/index.js) as follows in order to have routes without the /#/

```
export default new Router({
  mode: 'history',
  routes: [
    { path: '', name: 'Home', component: Home },
    { path: '/login', name: 'Login', component: Login },
    { path: '/signup', name: 'Signup', component: Signup },
    { path: '/chat', name: 'Chat', component: Chat }
  ]
})
```

Everything works as expected except for when I click the Sign Out button, then I get redirected to `http://localhost:8080/chat#`

So where can I get rid of the # at the end of the url?

**Comment by marshallswain** [comment]
Good catch!

Fixed in this commit: https://github.com/feathersjs/feathers-chat-vuex/commit/9daf4c1cd75b062c599359f1bc39ff5c597a968c

**Comment by lobosan** [comment]
Just updated the code but even though it doesn't show the # at the end of the URL, then it doesn't redirect to login after signing out

**Comment by marshallswain** [comment]
Oh, yep.  A handler for that will need to be added in the watcher in App.vue: https://github.com/feathersjs/feathers-chat-vuex/blob/master/src/App.vue#L19

@lobosan if you care to attempt a PR, that would be much appreciated, otherwise, I'll get to it eventually.  ;)
