### ISSUE TITLE
getbase changed their api in 3.5

### ISSUE THREAD

**Issue by FossPrime** [feathersjs/feathers-chat-vuex#45]
App.vue references `getbase/dist/css/styles.css` which is fine in [3.4.2](https://unpkg.com/getbase@3.4.2/)

but in [3.5.1](https://unpkg.com/getbase@3.5.1/), which is "compatible with" 3.4.2, the file moved to `getbase/css/styles.css` 

should we lock it to ~3.4.2 and call it a day
or use ^3.5.1, fix the path and expect everyone to re-run npm install?

**Comment by i06** [comment]
Hi, I got the same problem.
I solve it with change App.vue#line 8
```
import getbase/dist/css/styles.css
```
to
```
import '../node_modules/getbase/css/styles.css'
```
