### ISSUE TITLE
import 'getbase/dist/css/styles.css' causes client build error

### ISSUE THREAD

**Issue by Pokom** [feathersjs/feathers-chat-vuex#49]
After a fresh clone of the repository, I install and run as dev, and I get the following error thrown:

![image](https://user-images.githubusercontent.com/1080566/29925488-73f79a90-8e2e-11e7-835d-fcbe3b3cbe22.png)

I looked into getbase's node_modules directory, and the structure looks like so: 

![image](https://user-images.githubusercontent.com/1080566/29925542-98ecc802-8e2e-11e7-8fda-09d312585fb2.png)

I might need a bit more coffee to wake up, but if this is me not being dense, I've created PR #48 that I would be more then willing to alter if needed.

Thanks for the great example! I really appreciate it :)

**Comment by FossPrime** [comment]
Same issue as: [getbase changed their API 3.5](https://github.com/feathersjs/feathers-chat-vuex/issues/45)
