### ISSUE TITLE
rxjs related problem

### ISSUE THREAD

**Issue by exeze** [feathersjs/feathers-chat-vuex#55]
I get a rxjs related warning when running this example:
warning  in ./src/api/feathers-client.js
14:142-146 "export 'default' (imported as 'RxJS') was not found in 'rxjs'

Is this due to the recently updated feathers-vuex package which no longer needs rxjs and feathers-reactive?

How to reproduce the problem:
git clone https://github.com/feathers-plus/feathers-chat-vuex.git
cd feathers-chat-vuex
npm install
npm run dev

**Comment by duffett** [comment]
same as issue #54?

**Comment by exeze** [comment]
Yes, thanks!
