### ISSUE TITLE
fails to install with error: pathspec '1.0' did not match any file(s) known to git

### ISSUE THREAD

**Issue by L-K-Mist** [feathersjs/feathers-chat-vuex#59]
Trying to install on VS Code Linux Lite Ubuntu. Get this error. Also tried installing from zip file instead of git clone.

**Comment by jfmmm** [comment]
Got the same issue both on windows and on my work mac

**Comment by L-K-Mist** [comment]
Hi jfmmm,

The solution that worked for me:

Notice in the package.json the vuex entry:     `"feathers-vuex": "git://github.com/feathers-plus/feathers-vuex.git#1.0",`

The error comes out of our respective systems having difficulty with this kind of install.

What I did was remove that line. Do the `npm install` then `npm install feathers-vuex --save` 

That then installs it the "normal" way.

Best of luck!

**Comment by drunkod** [comment]
~/feathers-chat-vuex$ npm i
npm WARN deprecated feathers@2.2.4: Feathers v3 is out and has moved to @feathersjs/feathers. See https://docs.feathersjs.com/migrating.html for more information.
npm WARN deprecated feathers-authentication-client@0.3.3: Feathers v3 is out and this module has moved to @feathersjs/authentication-client. See https://docs.feathersjs.com/migrating.html for more information.
npm WARN deprecated feathers-hooks@2.1.2: Feathers v3 is out and this module has been integrated into Feathers core. See https://docs.feathersjs.com/migrating.html for more information.
npm WARN deprecated feathers-socketio@2.0.1: Feathers v3 is out and this module has moved to @feathersjs/socketio and @feathersjs/socketio-client. See https://docs.feathersjs.com/migrating.html for more information.
npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated feathers-errors@2.9.2: Feathers v3 is out and has moved to @feathersjs/errors. See https://docs.feathersjs.com/migrating.html for more information.
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated wrench@1.3.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout 1.0
npm ERR! error: pathspec '1.0' did not match any file(s) known to git.
npm ERR!

**Comment by jfmmm** [comment]
Oh yeah good catch.

Basically just replacing it with `"feathers-vuex": "^1.1.4"` fix it.
